development:
  adapter: postgresql
  encoding: unicode
  database: mint_development
  pool: 5
  username: will
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mint_test
  pool: 5
  username: will
  password:
